

const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Homepage",
        taskDescription: "Create the homepage layout for the new project",
        taskDate: "2025-10-12",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Login Bug",
        taskDescription: "Resolve issue with login form validation",
        taskDate: "2025-10-10",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Write Unit Tests",
        taskDescription: "Add unit tests for user authentication",
        taskDate: "2025-10-11",
        category: "Testing",
      },
    ],
  },
  {
    id: 2,
    firstName: "Vihaan",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Database Optimization",
        taskDescription: "Optimize SQL queries for faster response",
        taskDate: "2025-10-09",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Dashboard",
        taskDescription: "Add new charts to admin dashboard",
        taskDate: "2025-10-08",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Refactor Codebase",
        taskDescription: "Clean and organize code for maintainability",
        taskDate: "2025-10-07",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Client Meeting",
        taskDescription: "Discuss project requirements with client",
        taskDate: "2025-10-06",
        category: "Management",
      },
    ],
  },
  {
    id: 3,
    firstName: "Reyansh",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create API Endpoints",
        taskDescription: "Develop endpoints for user management",
        taskDate: "2025-10-11",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix CSS Issues",
        taskDescription: "Resolve styling problems in responsive layout",
        taskDate: "2025-10-10",
        category: "Frontend",
      },
    ],
  },
  {
    id: 4,
    firstName: "Isha",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Documentation",
        taskDescription: "Write technical documentation for API",
        taskDate: "2025-10-12",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Code Review",
        taskDescription: "Review PRs from junior developers",
        taskDate: "2025-10-11",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Optimize Images",
        taskDescription: "Compress images for faster load time",
        taskDate: "2025-10-10",
        category: "Frontend",
      },
    ],
  },
  {
    id: 5,
    firstName: "Ananya",
    email: "employee5@example.com",
    password: "123",
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Setup CI/CD",
        taskDescription: "Configure GitHub Actions for automated builds",
        taskDate: "2025-10-12",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test API",
        taskDescription: "Test endpoints using Postman",
        taskDate: "2025-10-11",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Client Feedback",
        taskDescription: "Collect feedback and update features",
        taskDate: "2025-10-10",
        category: "Management",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Dependencies",
        taskDescription: "Upgrade NPM packages to latest version",
        taskDate: "2025-10-09",
        category: "Development",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    firstName: "Rohit",
    email: "admin@example.com",
    password: "123",
    taskCounts: {
      active: 1,
      newTask: 1,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Review Employee Tasks",
        taskDescription: "Check all employee progress for the week",
        taskDate: "2025-10-12",
        category: "Management",
      },
    ],
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin")) || [];
  return { employees, admin };
};
